### ISSUE TITLE
not showing up

### ISSUE THREAD

**Issue by ghost** [srob650/tvmaze-plex-agent#2]
Is this not to be used for fixing matches and being able to select this? It shows up in agents tab but not for choices to pick when a show needs fixed.

**Comment by srob650** [comment]
I don't believe Plex allows you to use different agents on a per-show basis, so you either use it for your whole library or not.  If you set your TV library to use this agent then doing "Fix Incorrect Match" on a series in that library will indeed use this agent.  If you already had metadata for the show that was incorrect from another agent, you may want to use "Refresh All".

Thanks for trying this out, please do let me know if you run into any issues besides my date-based issue that is already noted in the readme :)
